# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mlamkadm <mlamkadm@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/07 18:17:37 by mlamkadm          #+#    #+#              #
#    Updated: 2025/01/07 18:17:37 by mlamkadm         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


