networks:
  backend:
    driver: bridge

services:
  test_network:
    build:
      context: ./solidity_module/test_net
      dockerfile: dockerfile
    container_name: we3_test_network
    networks:
      - backend

  module:
    build:
      context: ./solidity_module/module
      dockerfile: dockerfile
    container_name: web3_module
    volumes:
      - ./solidity_module/module:/app
    networks:
      - backend
    env_file:
      - ./solidity_module/.env
